[package]
name = "gamepad-bridge"
version = "0.5.1-42"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.0"
hidapi = "2.4.1"
version = "3.0.0"
termion = "2.0.1"
rand = "0.8.5"
