[package]
name = "gamepad-bridge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.0"
hidapi = "2.4.1"
regex = "1.9.3"
usb-device = "0.2.9"
